### ISSUE TITLE
Error after some time idel

### ISSUE THREAD

**Issue by ineiti** [dedis/columbus-united#40]
When I left columbus idle for 2-3 minutes, I got the following error:
```
Error: error: Error: Connection was closed abnormally, e.g., without sending or receiving a Close control frame.
```

**Comment by nkcr** [comment]
Yes, indeed this is something we want to fix.
This error is returned by the cothority client when the connection is not used after a while. Do you think this is something we should fix at the cothority client ?

**Comment by ineiti** [comment]
IIRC there is a timeout somewhere, I think it's even in the conode websocket server, that terminates unused connections after 30 seconds.

In the `cothority/v2/byzcoin`-api the web client reconnects when it detects a failing connection.
