### ISSUE TITLE
UI issues with Columbus

### ISSUE THREAD

**Issue by ineiti** [dedis/columbus-united#46]
The following UI issues have been seen when using https://wookiee.ch/columbus-dev/ on 20/12/08:
- the arrows between the blocks are too small to click on them -> widen the link target so you can easily click
- when opening the page, the latest block should be shown
- the chosen block should be centred in the block explorer, or be to the right if it's the latest block
- Block -> ForwardLink -> `Block xx` - when clicking on `Block xx`, it should directly go to that block - copy/paste is slow - what else should you do with the ID?
- `Search` -> it should automatically detect if it's a block-index (valid integer smaller 2**32), a block-ID (64 hex characters and a valid block) or an instance-ID (last choice)
- `Search` for instance: when clicking `Abort`, it should show `Abort the search` and not `Abort the research`...

**Comment by LucasTrg** [comment]
Thank you for the precious feedback ! 
3) and 4) are being adressed right now ! 
The other points should be quite fast to fix. We'll do our best to address all of them for the final version !

**Comment by nkcr** [comment]
> Search -> it should automatically detect if it's a block-index (valid integer smaller 2**32), a block-ID (64 hex characters and a valid block) or an instance-ID (last choice)

I don't agree there. For me it is better if the user can explicitly select the kind of research it can do. It help understand what you're doing, plus in the future we might have other research criteria that we won't be able to differentiate.

**Comment by ineiti** [comment]
> For me it is better if the user can explicitly select the kind of research it can do

I'm spoiled by google - throw in whatever you want, and it tries to give a reasonable answer. Why should I tell the interface what I'm looking for? The computer should do the work, not me. And it can do so much faster than me having to realize there is a multiple choice (which I didn't at first), and then making the correct choice.

If there is something that is ambivalent, a choice _could_ make sense. But even in that case I would prefer to get two (or more) results of possible answers.

One of the metrics of a UI is how many clicks it takes to fulfill an action. Less is better ;) Adding the multiple choice just adds two clicks, or three-four keystrokes for no additional gain to the user.

**Comment by nkcr** [comment]
then lets have both: keep the select with the default research criteria as "anything", but let the user choose a specific research criteria if he wants. Then we have the best of both worlds: a fast no-brain default option, but also the possibility to have a specific research if needed.

**Comment by ineiti** [comment]
Why would you want to tell the UI what you're looking for? So it can tell you: `nope, this is not a block-ID`?

The chance of two IDs being the same is very small...

Now if all of a sudden decimal numbers are not only block-numbers, but also something else, _then_ a dropdown list _might_ make sense. Even though I would prefer Google-style just to see all possibilities...

**Comment by LucasTrg** [comment]
I developed both version (one with a dropdown, and one that recognizes automatically what the input is). It could be interesting to do A/B testing during the validation UX study and see which one have more success :) !
