### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by ineiti** [dedis/columbus-united#51]
Here a list of UI issues that I think might make it even better  - using https://wookiee.ch/columbus-dev/ on 21/02/02:

* the arrows between the blocks are too small to click on them -> widen the link target so you can easily click
* upon visiting the page, the latest block should be selected, so that one can see the info
* the console shows me it's searching for `coin.svg`, but 
* arrows take a very long time to update - why? There is no need to fetch the block, or is it?

**Comment by sophiartl** [comment]
Thank you for your feedback! I believe the latest version of the explorer is on https://wookiee.ch/columbus/
Addressing the points you mention in order:
- Arrows have been slightly modified and made a little thicker although we could perhaps give them more clickable surface.
- This is a very good point, this feature was actually removed when the url could reflect the state of the chain. However it would be useful to have the last added block selected when no index is inputted in the url or in the other case, have the inputted block index selected.
- It seems the image was omitted when merging our branches with master, will get on to that asap!
- Indeed, for the arrows we need to fetch the SkipBlock corresponding to the hash of the backward link for each block. In this way, we can calculate the start-point of the arrow and display it on the view. We may find a way to optimise the loading of blocks to not fetch them twice - will reflect about this matter

I hope this clears some issues, thank you again for your valuable feedback!

**Comment by nkcr** [comment]
Thank you for this valuable feedback! I will ensure it gets incorporated in our next iteration.

**Comment by ineiti** [comment]
- if the clickable surface of the arrows is increased, it's easier to click. My proposition is to take _all_ the possible space: clicking between the blocks should be like clicking on the closes arrow
- for the backward-links, they can be calculated. Here is the method in the go-code: https://github.com/dedis/cothority/blob/master/skipchain/struct.go#L284 - it's the same for the backward-links, but with a negative sign on line 209.

**Comment by sophiartl** [comment]
Got it, that is indeed a good idea. 
Thank you for the method, it will really improve the performance of the explorer if the arrows do not take such a long time to load !
